name: TMS deploy

on:
  schedule:
    - cron: '*/20 * * * *'  # This runs the job every 10 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth
          pip install google-auth==2.30.0
          pip install google-auth-oauthlib==1.2.0
          pip install pandas==2.0.3
          pip install requests
          pip install openpyxl==3.1.3

      - name: Run Python script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json
          python main.py
